[package]
name = "uniden-fw-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.14.0"
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive", "wrap_help"] }
rust-lapper = "1.1.0"
